spring.application.name=kolochili
# Configuration de la base de données H2 en mémoire
spring.datasource.url=jdbc:h2:mem:kolochili_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permet d'activer l'interface web pour voir la base de données
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Afficher les requêtes SQL générées par l'ORM dans le terminal
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
